# Data preprocessing for credit card transaction data with Pandas

this notebook is describing how to preprocess data by using pandas.
Main concept is, 

<li> normalize dataset </li>
<li> split data to multiple chunks (training,validate,testing)</li>
<li> shuffle data by using ".sample(frac=1)" command</li>

In [24]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

df_csv = pd.read_csv('./data/creditcard.csv')
df_csv.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [25]:
df_norm = (df_csv - df_csv.min() ) / (df_csv.max() - df_csv.min() )
df_norm.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.000000,0.935192,0.766490,0.881365,0.313023,0.763439,0.267669,0.266815,0.786444,0.475312,...,0.561184,0.522992,0.663793,0.391253,0.585122,0.394557,0.418976,0.312697,0.005824,0.0
1,0.000000,0.978542,0.770067,0.840298,0.271796,0.766120,0.262192,0.264875,0.786298,0.453981,...,0.557840,0.480237,0.666938,0.336440,0.587290,0.446013,0.416345,0.313423,0.000105,0.0
2,0.000006,0.935217,0.753118,0.868141,0.268766,0.762329,0.281122,0.270177,0.788042,0.410603,...,0.565477,0.546030,0.678939,0.289354,0.559515,0.402727,0.415489,0.311911,0.014739,0.0
3,0.000006,0.941878,0.765304,0.868484,0.213661,0.765647,0.275559,0.266803,0.789434,0.414999,...,0.559734,0.510277,0.662607,0.223826,0.614245,0.389197,0.417669,0.314371,0.004807,0.0
4,0.000012,0.938617,0.776520,0.864251,0.269796,0.762975,0.263984,0.268968,0.782484,0.490950,...,0.561327,0.547271,0.663392,0.401270,0.566343,0.507497,0.420561,0.317490,0.002724,0.0

In [26]:

df_norm.iloc[1][1:29]
df_norm.iloc[1][30]

0.0

In [27]:
NORM_FILE='./data/creditcard_norm.csv'
df_norm.to_csv(NORM_FILE, index=False, header=False)

In [28]:
# split normalized data by label
df_norm_fraud=df_norm[ df_norm.Class==1.0] #fraud
df_norm_nonfraud=df_norm[ df_norm.Class==0.0] #non_fraud

# split non_fraudfor 60%,20%,20% (training,validation,test)
df_norm_nonfraud_train,df_norm_nonfraud_validate,df_norm_nonfraud_test = \
    np.split(df_norm_nonfraud,[int(.6*len(df_norm_nonfraud)),int(.8*len(df_norm_nonfraud))])
# split fraud data to 50%,50% (validation and test)
df_norm_fraud_validate,df_norm_fraud_test = \
    np.split(df_norm_fraud,[int(0.5*len(df_norm_fraud))])
print('number of non fraud training, test, validation dataset = ',\
len(df_norm_nonfraud_train),\
len(df_norm_nonfraud_test),\
len(df_norm_nonfraud_validate))
      
print('number of fraud test,fraud validation dataset =',\
len(df_norm_fraud_test),\
len(df_norm_fraud_validate))

#create train,validate and test dataset with shuffle
df_train = df_norm_nonfraud_train.sample(frac=1) 
df_validate = df_norm_nonfraud_validate.append(df_norm_fraud_validate).sample(frac=1)
df_test = df_norm_nonfraud_test.append(df_norm_fraud_test).sample(frac=1)

print 'size of train,validate,test data =',len(df_train),len(df_validate),len(df_test)

('number of non fraud training, test, validation dataset = ', 170589, 56863, 56863)
('number of fraud test,fraud validation dataset =', 246, 246)
size of train,validate,test data = 170589 57109 57109

# Training data set

In [29]:
df_train.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
159846,0.653960,0.994440,0.765953,0.807044,0.253598,0.768589,0.257320,0.265826,0.783348,0.495935,...,0.564832,0.542583,0.664601,0.392792,0.600635,0.358630,0.416430,0.311987,0.000039,0.0
36776,0.223847,0.941220,0.769319,0.843473,0.267792,0.778211,0.253344,0.266262,0.788193,0.446112,...,0.564783,0.523146,0.665778,0.316106,0.551206,0.333208,0.419669,0.317717,0.000039,0.0
73035,0.317989,0.943973,0.773825,0.843239,0.306767,0.772997,0.255055,0.271795,0.780835,0.451908,...,0.561573,0.552387,0.673772,0.396450,0.538665,0.371704,0.425698,0.313827,0.000212,0.0
156260,0.623183,0.947559,0.780913,0.853596,0.371119,0.773915,0.268569,0.273704,0.785388,0.427252,...,0.565912,0.541062,0.664909,0.472773,0.578883,0.424164,0.416922,0.316218,0.004323,0.0
2256,0.010394,0.977896,0.758391,0.869791,0.305722,0.752537,0.265998,0.257369,0.788043,0.481708,...,0.554006,0.491249,0.666001,0.477012,0.599689,0.376650,0.418852,0.314106,0.000973,0.0

# Test data set

In [30]:
df_test.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
273774,0.958904,0.945167,0.774487,0.875228,0.227278,0.765247,0.266729,0.265748,0.788674,0.479787,...,0.561679,0.518685,0.660648,0.459015,0.603621,0.390414,0.422669,0.316114,0.000467,0.0
261981,0.927485,0.993764,0.769756,0.787331,0.267158,0.774262,0.254221,0.270104,0.780702,0.465429,...,0.561637,0.517479,0.663442,0.383752,0.604682,0.543243,0.414582,0.312112,0.001541,0.0
273067,0.957255,0.912098,0.793833,0.826742,0.295973,0.762403,0.252298,0.267936,0.794169,0.437742,...,0.564464,0.521599,0.660692,0.435123,0.642749,0.384170,0.401864,0.313718,0.000984,0.0
252788,0.902634,0.941462,0.780733,0.838821,0.290330,0.772977,0.259360,0.272570,0.787013,0.418952,...,0.563119,0.519496,0.656935,0.290815,0.648394,0.401774,0.414934,0.312023,0.001714,0.0
273429,0.958297,0.993340,0.765582,0.824819,0.253608,0.766110,0.263462,0.262885,0.784811,0.501292,...,0.558979,0.497789,0.669555,0.384363,0.567052,0.275285,0.417694,0.312637,0.000039,0.0

# Validate data set

In [31]:
df_validate.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
218267,0.817399,0.994460,0.757625,0.804437,0.198703,0.765546,0.257372,0.264055,0.783162,0.435827,...,0.562615,0.507757,0.665952,0.232055,0.576666,0.381421,0.415278,0.311628,0.002997,0.0
180616,0.721214,0.924666,0.782946,0.831813,0.190927,0.764579,0.258103,0.274213,0.790166,0.440624,...,0.559019,0.490665,0.663499,0.485732,0.639555,0.415175,0.413515,0.310747,0.006506,0.0
215932,0.811861,0.993317,0.767575,0.799144,0.245810,0.770539,0.251940,0.269565,0.781157,0.459680,...,0.564846,0.539882,0.664961,0.493571,0.601463,0.455206,0.414711,0.311539,0.000866,0.0
207128,0.790147,0.996977,0.758945,0.806687,0.203366,0.764429,0.254372,0.263195,0.781797,0.450289,...,0.567342,0.557755,0.663301,0.252945,0.595670,0.447022,0.415648,0.311590,0.000973,0.0
204859,0.784058,0.961924,0.766434,0.849226,0.224125,0.770500,0.258358,0.267605,0.781708,0.498991,...,0.561251,0.529163,0.669633,0.330218,0.441919,0.255702,0.416564,0.311063,0.000097,0.0

In [37]:
len(df_validate[df_validate.Class==1])

56863

# Write into files
write training, testing and validation data into files

In [47]:
TRAIN_FILE='creditcard_training.csv'
TEST_FILE='creditcard_tesring.csv'
VALIDATE_FILE='creditcard_validation.csv'

df_train.to_csv(TRAIN_FILE, index=False, header=False)
df_validate.to_csv(VALIDATE_FILE,index=False,header=False)
df_test.to_csv(TEST_FILE,index=False,header=False)

In [48]:
!head $TRAIN_FILE

0.261400990787,0.920081173661,0.739618573549,0.846635483264,0.211875205478,0.747219863054,0.265201445517,0.289390808274,0.777545474788,0.4048072684,0.491891094326,0.265551327178,0.664452868446,0.44376239723,0.631950627163,0.284476651591,0.470581452676,0.742050573509,0.56383930726,0.565842969614,0.604834165582,0.573748782649,0.535247306924,0.693081227577,0.467797602723,0.641372908539,0.389837325093,0.407267961081,0.311111755229,0.037989720978,0.0
0.506742210288,0.973964159764,0.738640423594,0.82010776525,0.196860877767,0.753955093069,0.255521771603,0.265874836226,0.78235249496,0.563993732223,0.471831807744,0.238617297587,0.770681953793,0.516385949707,0.631182799881,0.355103125787,0.413136868551,0.734736065727,0.642395251379,0.653631887907,0.590838866382,0.564060756051,0.494823338943,0.661687908698,0.395672246834,0.558785394119,0.243907627883,0.416475806625,0.314553037595,0.0225595107422,0.0
0.307450576416,0.931388300646,0.777800900498,0.851944763997,0.253852162842,0.767592518089,0.261924746163,0.267997402791,0.785027298782,0.475271382572,0.510565687622,0.197434030932,0.730673950842,0.563969835634,0.620954951733,0.285587505166,0.439796241804,0.722815138497,0.630875213988,0.619066800214,0.577435938356,0.559816101936,0.52513238944,0.666030336332,0.333939739493,0.581186347824,0.48226924827,0.408539435121,0.309065382975,0.000356542873113,0.0
0.219495115515,0.915546731603,0.74432947963,0.883596070631,0.330142687289,0.781353086463,0.255605608815,0.252317447357,0.793620772282,0.46211257395,0.509356016529,0.325531502299,0.71498975005,0.384458804111,0.653438557261,0.393877242028,0.44182851877,0.731468986079,0.711578081448,0.625330096733,0.588038704607,0.568787493231,0.53857973695,0.667555311917,0.341108543408,0.595824074935,0.421299083761,0.417322910831,0.315741318067,0.0,0.0
0.290302791796,0.93753146783,0.783637836968,0.867911943667,0.374920550074,0.76428204291,0.26268887506,0.266433577981,0.790384958377,0.395966445965,0.524413820766,0.356588075822,0.711859027221,0.420738124564,0.674478560928,0.378543746379,0.455429787231,0.732790201019,0.681260675926,0.655559574764,0.579371192558,0.561103240895,0.496322900518,0.665916468142,0.449346996228,0.578743615979,0.434182487915,0.411365225628,0.312755540938,0.00045696652078,0.0
0.201241955646,0.978046997261,0.757436943031,0.850163496235,0.232834762109,0.756274879866,0.259856708339,0.260988865528,0.786024967093,0.443460294226,0.52203573192,0.334414799602,0.729250859434,0.432079808442,0.643999250767,0.276263955928,0.407320821223,0.733226463538,0.723441109101,0.558180338219,0.576522757908,0.550757479014,0.438599935624,0.668149579407,0.424550139955,0.571703345824,0.540630879369,0.415558883995,0.313498686564,0.00321511368113,0.0
0.481243344599,0.977364869709,0.77333480782,0.843300622486,0.371926656942,0.766466688324,0.264972407122,0.264838311163,0.786856683331,0.44507262788,0.513309723046,0.330764021628,0.729237665223,0.450529428907,0.60621405911,0.225374560674,0.472821375095,0.740933826537,0.690818750297,0.534146661444,0.57920104694,0.559760010394,0.503737891186,0.663122812443,0.374093277548,0.614200130743,0.438444295066,0.416857999198,0.313787464686,0.000295821597779,0.0
0.00853627482754,0.928574883932,0.781660778734,0.854177543986,0.224992691449,0.761768037916,0.25373925345,0.266893783789,0.789924855144,0.48633722562,0.507117913366,0.214958780657,0.688603734356,0.326775205704,0.650961773728,0.295751391486,0.44667922474,0.733815680616,0.619539906686,0.553784614441,0.580084535318,0.557882204688,0.486651959721,0.665667345161,0.432023824024,0.583134206377,0.486392482275,0.418469719497,0.31766450816,0.000194619472223,0.0
0.197532293162,0.947373996336,0.771476037129,0.852745028254,0.207402306323,0.778687069508,0.303928436361,0.262291957041,0.798331838485,0.470955704498,0.498525894145,0.245865232693,0.70107345426,0.440310412091,0.633095476134,0.351387231906,0.460429216739,0.712673852276,0.68028647721,0.603737723382,0.583074025119,0.559751029647,0.500187236363,0.662649913601,0.521326917325,0.583110713344,0.479090740379,0.422754442324,0.316481960662,0.000447624786113,0.0
0.426900550951,0.976296528093,0.767369328449,0.841168868839,0.282796488265,0.763032696462,0.252193939246,0.267997840643,0.782178268368,0.457439902134,0.506035492495,0.277689815427,0.724380165021,0.484716551159,0.65769816417,0.399927387647,0.45542112776,0.721064578434,0.591101863191,0.566818712893,0.581694798902,0.554513206209,0.438893955664,0.667808001353,0.429450671362,0.582015193036,0.402735220058,0.415398388665,0.313890650568,0.00432522315069,0.0